services:
  # db:
  #   image: arm64v8/mysql:8.0
  #   # image: mysql:8.0-bullseye
  #   # build: ./mysql
  #   # restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: supersecret
  #     MYSQL_DATABASE: cascade
  #     MYSQL_USER: cas
  #     MYSQL_PASSWORD: supersecret
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql

  web:
    image: php:8.3.3-apache
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    # build: ./web-server
    expose:
      - 8888
    ports:
      - "8888:80"
    volumes:
      - ./app:/var/www/html

  # mailcatcher:
  #  image: tophfr/mailcatcher
  #  ports:
  #    - "9025:80"

  # phpmyadmin:
  #  image: 'phpmyadmin/phpmyadmin'
  #  depends_on:
  #    - db
  #  ports:
  #    - "8181:80"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: 'supersecret'
  #  links:
  #    - db:db
 